# Generated by Django 5.2 on 2026-08-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_product_sku'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='transaction_quantity_positive'),
        ),
    ]
